### ISSUE TITLE
Small delays specified in data sheet are not present for all commands over i2c

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_SCD30#14]
The CircuitPython library had no delays noted in https://github.com/adafruit/Adafruit_CircuitPython_SCD30/issues/13 which has now been addressed. A quick review of this library shows a delay (of 4ms) for the `Read measurement`:

https://github.com/adafruit/Adafruit_SCD30/blob/24ee7a335f522df5dd74bcf4ae30beda8fc874d1/Adafruit_SCD30.cpp#L268-L326

but not for the `Get data ready status`:

https://github.com/adafruit/Adafruit_SCD30/blob/24ee7a335f522df5dd74bcf4ae30beda8fc874d1/Adafruit_SCD30.cpp#L123-L125

https://github.com/adafruit/Adafruit_SCD30/blob/24ee7a335f522df5dd74bcf4ae30beda8fc874d1/Adafruit_SCD30.cpp#L345-L352

Would be useful for someone else to check this library and confirm this.

**Comment by ladyada** [comment]
great, please submit a PR to address it!

**Comment by caternuson** [comment]
I'm looking into this right now. It seems like it might explain #12.

**Comment by caternuson** [comment]
Closing. Added with #15.

Thanks for pointing this out.
