### ISSUE TITLE
Getting odd values with M0 (other?) boards

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_SCD30#6]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=19&t=175010

I've recreated same behavior on QT PY:
![Screenshot from 2021-02-05 13-55-03](https://user-images.githubusercontent.com/8755041/107093324-e5fb6280-67b9-11eb-8e35-8be9d8e1dfdb.png)

And also Itsy M0:
![Screenshot from 2021-02-05 13-53-25](https://user-images.githubusercontent.com/8755041/107093348-ef84ca80-67b9-11eb-91af-f9ff3696a235.png)

But seems to work just fine on Itsy M4:
![Screenshot from 2021-02-05 13-51-06](https://user-images.githubusercontent.com/8755041/107093376-fb708c80-67b9-11eb-922c-65f3a82a1e08.png)

**Comment by ladyada** [comment]
!? can you try turning on i2c debug in busio?

**Comment by caternuson** [comment]
This is on QT PY, running the `adafruit_scd30_test ` example, and with `#define DEBUG_SERIAL Serial` enabled in `Adafruit_I2CDevice.cpp`, and uploading after a complete power cycle.

Looks like the reset failed maybe?

![Screenshot from 2021-02-05 14-14-50](https://user-images.githubusercontent.com/8755041/107095022-ecd7a480-67bc-11eb-8f45-59a200fcc2ad.png)

**Comment by ladyada** [comment]
can you compare the data trace with an M4?

**Comment by caternuson** [comment]
**Itsy M4**

![Screenshot from 2021-02-05 14-33-14](https://user-images.githubusercontent.com/8755041/107096226-18f42500-67bf-11eb-8ec3-97c83f1f2a88.png)

**Comment by ladyada** [comment]
try initing these to zero
https://github.com/adafruit/Adafruit_SCD30/blob/master/Adafruit_SCD30.cpp#L293

**Comment by ladyada** [comment]
also this is running past the buffer end
https://github.com/adafruit/Adafruit_SCD30/blob/master/Adafruit_SCD30.cpp#L286

**Comment by caternuson** [comment]
OK, back to **QT PY** with initing those values to zero. But nothing done for the buffer index.

![Screenshot from 2021-02-05 14-42-40](https://user-images.githubusercontent.com/8755041/107096856-7d63b400-67c0-11eb-8d14-f64c998cb67d.png)

**Comment by ladyada** [comment]
yay ok! PR plz :)

**Comment by caternuson** [comment]
nice spot! thanks.

guess we'll see if/when that buffer index issue causes grief.

**Comment by caternuson** [comment]
Looks resolved:
https://forums.adafruit.com/viewtopic.php?f=19&t=175010#p853221

Thanks again @ladyada for the assist!

**Comment by kevinjwalters** [comment]
This sort of thing (stack variables used before initialisation) could easily be detected by static analysis of the code as a prevention measure in the same way that `pylint` runs over the CircuitPython libraries.

The `gcc`/`g++` compiler has enough smarts in it to pick this up too with `-Wuninitialized` and/or `-Wmaybe-uninitialized`. Antique versions of `gcc` may incorrectly inhibit this due to confusion from `memcpy()`.

**Comment by ladyada** [comment]
@kevinjwalters yes, please add a check update to the Arduino CI!
