### ISSUE TITLE
Adafruit_SCD30_Humidity::getSensor may set type incorrectly

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_SCD30#8]
Two comments, class name and `type` assignment do not match here:

https://github.com/adafruit/Adafruit_SCD30/blob/55028d61b58af9f474342d469a0bd1b7934f7181/Adafruit_SCD30.cpp#L412-L430

This sensors does not appear to be capable of measuring pressure??

**Comment by ladyada** [comment]
yeah thats a typo or copy paste error
@kevinjwalters please submit a PR to fix it

**Comment by kevinjwalters** [comment]
I don't own this sensor and have never used this code. I was just reading a forum post about it and glanced at the code.

**Comment by ladyada** [comment]
you dont need to own a sensor to fix typos :)

**Comment by caternuson** [comment]
Closing. Fixed with #10.
